### PR TITLE
Add support for TradeTax > ExemptionReasonCode

### PR DESCRIPTION
**Pull request by pableu**

### CODE REVIEW

**Comment by PATROMO** [comment]
@pableu see code style test.

**Comment by pableu** [comment]
@PATROMO fixed, thanks :)

**Comment by PATROMO** [comment]
@pableu thanks. Can you extend the Test `tests/zugferd211/Tests/BuilderTest.php:169` with your new property?

**Comment by pableu** [comment]
I can, but I'd have to set it to null __or__ also modify `tests/zugferd211/Tests/official_example_xml/zugferd_2p1_XRECHNUNG_Einfach.xml`. 

The former seems a bit silly, and the latter feels wrong because it's an "official example" and I'd feel bad about modifying it.

Also, anything else than "null" won't make sense in the context of the sample document because the sample invoice there is __including__ vat, so adding a (Vat)ExemptionReason(Code) other than "null" doesn't make sense.

What do you think? Silly test with `null`? Or no test? 

Or a whole new test? I don't feel confident about adding a completely new test and new test data.

**Comment by Lorenzschaef** [comment]
@pableu, you can extend the test `testBuildXRechnungExtendedExample`, which already has more elements than the official example.

**Comment by BolZer** [comment]
This issue is done with #60. Gonna close this PR.

**Pull request closed without merging**
